### ISSUE TITLE
Invalid YAML

### ISSUE THREAD

**Issue by florian42** [florian42/obsidian-clipper#3]
The following yaml generated by the extension is invalid:

```yaml
link: "https://www.arahansen.com/how-children-types-work-in-react-18-and-typescript-4/"
title: "How Children Types Work In React 18 And TypeScript 4"
timestamp: "1/26/2023"
domain: "www.arahansen.com"
excerpt: "One of the coolest features of React is that everything is 'just JavaScript' (or TypeScript!) so the library mostly doesn't care what you provide as children as long as it can be rendered to the UI. We even can have functions as children (aka, render props)!

But I said you can render 'mostly' anything. There are some exceptions and this presents a challenge for defining accurate type definitions for React children.


React type definitions

The React type definitions (@types/react) are maintain"
word_count: "9855"
status: "unread"
```
URL: https://www.arahansen.com/how-children-types-work-in-react-18-and-typescript-4/
